<?php

namespace zaboy\test\async\Promise;

use zaboy\async\Promise\Promise;
use zaboy\async\Promise\PromiseInterface;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-24 at 00:05:36.
 */
class PromiseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Promise
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers zaboy\async\Entity\Promise::getState
     * @todo   Implement testGetState().
     */
    public function testGetState()
    {
        $this->object = new Promise;
        $this->assertEquals(PromiseInterface::PENDING, $this->object->getState());
    }

}
