<?php

namespace zaboy\test\Callback\Interruptor;

use zaboy\Callback\Callback;
use zaboy\test\Callback\CallbackTestDataProvider;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-20 at 12:54:48.
 */
class CallbackTestCallableProvider extends CallbackTestDataProvider
{

    public function pause($val)
    {
        sleep($val);
        return $val . ' sec.';
    }

    public function increment($val)
    {
        return $val + 1;
    }

}
