<?php

namespace zaboy\test\async\Promise\Fulfilled;

use zaboy\async\Promise\Promise;
use zaboy\async\Promise\PromiseInterface;
use zaboy\async\Promise\Promise\Pending as PendingPromise;
use zaboy\async\Promise\TimeIsOutException;
use zaboy\async\Promise\RejectedException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-24 at 00:05:36.
 */
class PromiseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Promise
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        global $container;



//        $container = include 'config/container.php';
//        InsideConstruct::setContainer($container);
    }

    //====================== getState(); =======================================
    public function testResolvePendingPromise()
    {
        $promise = new Promise;
        $promise->resolve('foo');
        $this->assertEquals(PromiseInterface::FULFILLED, $promise->getState());
    }

    //====================== wait(); ===========================================
    //====================== resolve(); ========================================
    //====================== reject(); =========================================
    //====================== then(); ===========================================
}
