<?php

namespace zaboy\test\Callback;

use zaboy\Callback\Callback;
use zaboy\test\Callback\CallbackTestDataProvider;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-20 at 12:54:48.
 */
class CallbackTest extends CallbackTestDataProvider
{

    /**
     * @var Callback
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new Callback;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers zaboy\Callback\Callback::__invoke
     * @dataProvider provider_mainType()
     */
    public function test__invoke($callable, $val, $expected)
    {
        $callback = new Callback($callable);
        /* @var $callback Callback */
        $this->assertEquals($expected, $callback($val));
    }

    /**
     * @covers zaboy\Callback\Callback::__sleep
     * @dataProvider provider_mainType()
     */
    public function test__sleep($callable, $val, $expected)
    {
        $callback = new Callback($callable);
        /* @var $callback Callback */
        $this->assertEquals('array', gettype($callback->__sleep()));
    }

    /**
     * @covers zaboy\Callback\Callback::__wakeup
     * @dataProvider provider_mainType()
     */
    public function test__wakeup($callable, $val, $expected)
    {
        $callback = new Callback($callable);
        /* @var $callback Callback */
        $wakeupedCallback = unserialize(serialize($callback));
        $this->assertEquals($expected, $wakeupedCallback($val));
    }

}
