<?php

namespace zaboy\test\async\Entity;

use zaboy\async\Entity\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-20 at 14:36:01.
 */
class EntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Async
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers zaboy\async\Entity::getId
     */
    public function test__getId()
    {
        $this->object = new Entity();
        $this->assertTrue(
                $this->object->isId($this->object->getId())
        );
    }

    /**
     * @covers zaboy\async\Entity::getData
     */
    public function test__getData()
    {
        $this->object = new Entity();
        $this->assertArrayHasKey(
                'id', $this->object->getData()
        );
    }

}
