<?php
/**
 * Created by PhpStorm.
 * User: victorsecuring
 * Date: 30.12.16
 * Time: 4:37 PM
 */

namespace zaboy;


use Composer\Script\Event;
use zaboy\installer\Install\AbstractCommand;
use zaboy\installer\Install\InstallerInterface;
class InstallCommands extends AbstractCommand
{
    /**
     * @param null $dir
     * @return InstallerInterface[]
     */
    public static function getInstallers($dir = null)
    {
        if (!isset($dir)) {
            $dir = __DIR__;
        }
        return parent::getInstallers($dir);
    }

    public static function install(Event $event)
    {
        $event->getIO()->write("If you wont use http cron hook to queue, you had add to path instance which will be created using CronReceiverFactory.
        \nFor mor details read CronReceiver -> 'https://github.com/avz-cmf/zaboy/tree/master/CronReceiver.md'.");
        parent::install($event); // TODO: Change the autogenerated stub
    }

}